=== L-Acoustics/avdecc/resources/schemas/AVE/v2/schema.json
{
	"$schema": "http://json-schema.org/draft/2020-12/schema#",
	"title": "AEM Files Schema",
	"description": "JSON validation schema for ATDECC Entity Model files",
	"type": "object",
	"schema_version": "2025.03.11",
	"properties": {
		"_dump_source (informative)": {
			"type": "string",
			"description": "Name and Version of the tool used to generate the dump."
		},
		"dump_version": {
			"type": "integer",
			"minimum": 2,
			"maximum": 2
		},
		"entity_model": {
			"$ref": "../../AEM/v2/schema.json"
		},
		"entity_model_id": {
			"$ref": "../../common/2025.03.11/schema.json#/$defs/uniqueIdentifier"
		}
	},
	"required": [
		"dump_version",
		"entity_model",
		"entity_model_id"
	]
}

=== L-Acoustics/avdecc/tests/data/SimpleEntityModel.json
{
    "_dump_source (informative)": "Hive v1.3.0 using L-Acoustics AVDECC Controller v4.0.0-beta8",
    "dump_version": 1,
    "entity_model": {
        "entity_descriptor": {
            "configuration_descriptors": [
                {
                    "_index (informative)": 0,
                    "audio_unit_descriptors": [
                        {
                            "_index (informative)": 0,
                            "control_descriptors": null,
                            "static": {
                                "clock_domain_index": 0,
                                "control_counts": 0,
                                "localized_description": {
                                    "index": 3,
                                    "offset": 0
                                },
                                "sampling_rates": [
                                    "0x00017700"
                                ]
                            },
                            "stream_port_input_descriptors": [
                                {
                                    "_index (informative)": 0,
                                    "audio_cluster_descriptors": [
                                        {
                                            "_index (informative)": 0,
                                            "static": {
                                                "block_latency": 0,
                                                "channel_count": 1,
                                                "format": "MBLA",
                                                "localized_description": {
                                                    "index": 4,
                                                    "offset": 0
                                                },
                                                "path_latency": 0,
                                                "signal_index": 0,
                                                "signal_output": 0,
                                                "signal_type": "INVALID"
                                            }
                                        },
                                        {
                                            "_index (informative)": 1,
                                            "static": {
                                                "block_latency": 0,
                                                "channel_count": 1,
                                                "format": "MBLA",
                                                "localized_description": {
                                                    "index": 5,
                                                    "offset": 0
                                                },
                                                "path_latency": 0,
                                                "signal_index": 0,
                                                "signal_output": 0,
                                                "signal_type": "INVALID"
                                            }
                                        },
                                        {
                                            "_index (informative)": 2,
                                            "static": {
                                                "block_latency": 0,
                                                "channel_count": 1,
                                                "format": "MBLA",
                                                "localized_description": {
                                                    "index": 6,
                                                    "offset": 0
                                                },
                                                "path_latency": 0,
                                                "signal_index": 0,
                                                "signal_output": 0,
                                                "signal_type": "INVALID"
                                            }
                                        },
                                        {
                                            "_index (informative)": 3,
                                            "static": {
                                                "block_latency": 0,
                                                "channel_count": 1,
                                                "format": "MBLA",
                                                "localized_description": {
                                                    "index": 0,
                                                    "offset": 1
                                                },
                                                "path_latency": 0,
                                                "signal_index": 0,
                                                "signal_output": 0,
                                                "signal_type": "INVALID"
                                            }
                                        }
                                    ],
                                    "audio_map_descriptors": null,
                                    "control_descriptors": null,
                                    "static": {
                                        "clock_domain_index": 0,
                                        "control_counts": 0,
                                        "flags": [
                                            "CLOCK_SYNC_SOURCE",
                                            "SYNC_SAMPLE_RATE_CONV"
                                        ]
                                    }
                                }
                            ],
                            "stream_port_output_descriptors": null
                        }
                    ],
                    "avb_interface_descriptors": [
                        {
                            "_index (informative)": 0,
                            "static": {
                                "clock_accuracy": 34,
                                "clock_class": 248,
                                "clock_identity": "0x001B92FFFE021995",
                                "domain_number": 0,
                                "flags": [
                                    "GPTP_GRANDMASTER_SUPPORTED",
                                    "GPTP_SUPPORTED",
                                    "SRP_SUPPORTED"
                                ],
                                "localized_description": {
                                    "index": 2,
                                    "offset": 1
                                },
                                "log_announce_interval": 0,
                                "log_pdelay_interval": 0,
                                "log_sync_interval": 253,
                                "mac_address": "00:1B:92:02:19:95",
                                "offset_scaled_log_variance": 17258,
                                "port_number": 1,
                                "priority1": 248,
                                "priority2": 248
                            }
                        }
                    ],
                    "clock_domain_descriptors": [
                        {
                            "_index (informative)": 0,
                            "static": {
                                "clock_sources": [
                                    0
                                ],
                                "localized_description": {
                                    "index": 0,
                                    "offset": 2
                                }
                            }
                        }
                    ],
                    "clock_source_descriptors": [
                        {
                            "_index (informative)": 0,
                            "static": {
                                "clock_source_location_index": 0,
                                "clock_source_location_type": "STREAM_INPUT",
                                "clock_source_type": "INPUT_STREAM",
                                "localized_description": {
                                    "index": 6,
                                    "offset": 1
                                }
                            }
                        }
                    ],
                    "control_descriptors": [
                        {
                            "_index (informative)": 0,
                            "static": {
                                "block_latency": 0,
                                "control_domain": 0,
                                "control_latency": 0,
                                "control_type": "0x90E0F00000000001",
                                "control_value_type": {
                                    "read_only": false,
                                    "unknown": false,
                                    "value_type": "CONTROL_LINEAR_UINT8"
                                },
                                "localized_description": {
                                    "index": 3,
                                    "offset": 1
                                },
                                "number_of_values": 1,
                                "reset_time": 0,
                                "signal_index": 0,
                                "signal_output": 0,
                                "signal_type": "INVALID",
                                "values": {
                                    "type": "CONTROL_LINEAR_UINT8",
                                    "values": [
                                        {
                                            "default": 0,
                                            "maximum": 255,
